when:
  - event: push
    branch: main
  - event: pull_request

steps:
  test:
    image: rust:1
    commands:
      - cargo fmt --all -- --check
      - cargo clippy --all-targets -- -D warnings
      - cargo test --all-targets
